### ISSUE TITLE
import-key-pair forces Cloud9 to hang

### ISSUE THREAD

**Issue by Bill-M123** [aws-samples/eks-workshop#1005]
I have followed every command from the beginning, and this command:

aws ec2 import-key-pair --key-name "eksworkshop" --public-key-material file://~/.ssh/my-key.pub

causes cloud9 to hand and not return a prompt or error message of any kind.  Any ideas?

**Comment by brentley** [comment]
For now, skip it. I believe we only use this in the ML lab so you won’t
be missing any functionality elsewhere. 

We will take a deeper look to see if we can reproduce in our side. 


On November 24, 2020, GitHub <notifications@github.com> wrote:
> I have followed every command from the beginning, and this command:
>
> aws ec2 import-key-pair --key-name "eksworkshop" --public-key-material

> file://~/.ssh/my-key.pub
>
> causes cloud9 to hand and not return a prompt or error message of any

> kind. Any ideas?
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub <https://github.com/aws-

samples/eks-workshop/issues/1005>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAB3SEDWNMYMIS44MQWPVT3SRQQGZANCNFSM4UBNVVAQ>.

**Comment by Bill-M123** [comment]
Skipping and closing.
