### ISSUE TITLE
failed to run `helm install kube-ops-view` 

### ISSUE THREAD

**Issue by riita10069** [aws-samples/eks-workshop#1508]
Page: https://www.eksworkshop.com/beginner/080_scaling/install_kube_ops_view/

```
➜  helm install kube-ops-view \
stable/kube-ops-view \
--set service.type=LoadBalancer \
--set rbac.create=True
Error: INSTALLATION FAILED: repo stable not found
```

Therefore, "stable" has to add to my repositories.

**Comment by ROunofF** [comment]
I'm curious to know how did you end up having helm installed but not the stable repo? It was previously installed ?

I'm asking because the stable repo is added through the helm install instructions we provide (https://www.eksworkshop.com/beginner/060_helm/helm_intro/install/index.html) which is mentioned at the top of the page ?

**Comment by riita10069** [comment]
I didn't realize I was installing it in the first step.
I was using Cloud9 with helm installed by `eksinit.sh`.

**Comment by ROunofF** [comment]
Blueprint was updated so it's done for the user. Use the note above to install helm + add repo.
