### ISSUE TITLE
Istio version, and therefor dir name has changed

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#243]
In https://eksworkshop.com/servicemesh/download/, the new version is 1.0.5, so we'll need to change the CL to 

```
cd istio-1.0.3
```

**Comment by cloudymind** [comment]
Tested section with 1.0.5 and the downstream steps are still compatible. I would suggest setting the dependency to a specific point release other than GetLatest in order to avoid introducing breaking changes to the workshop.

In general, best practice cautions against using the :latest tag when deploying containers in production since it's harder to track which version of the image is running and complicates rollback.
