### ISSUE TITLE
Provide cost usage

### ISSUE THREAD

**Issue by gfediere** [aws-samples/eks-workshop#772]
Hi,

Could be helpful to provide a cost usage for this workshop in case customers would like to run it on their own.

Br,

**Comment by Rick-2CA** [comment]
Some safe guards we could use to help slow down costs would be helpful too.  At this point I'm abandoning running the cluster and plan to just read through the material due due to costs.  

This is after figuring out how to replace the M5.Large machines with T3.Smalls - which helped with billing, but I've no idea how it's negatively impacted the workshop.  A few things haven't gone as designed and it's made it difficult to tell if it's performance due to my action or something else.  Restarting the Cloud9 session by doing this over days has caused me to run into variables missing at times too because it was assumed my session still had the required information.

**Comment by johnnybaloney** [comment]
Just got burnt by this. $50 bill and only this much thanks to the limit alert email that also had a link to the billing page. Incidentally, the 'free' tier allowance must be really meagre if a handful of chapters from the workshop can exhaust it within days. 

IMO the problem is [this page](https://www.eksworkshop.com/030_eksctl/launcheks/). The YAML doesn't show the instance type, which I understand defaults to `m5.large`, and if shown might have at the very least prompted me to research the cost. No information on the page itself on the cost involved either.

The guys in the [video here](https://www.eksworkshop.com/020_prerequisites/) mention to choose `t2.micro` for Cloud9 if you "really want to save money", which is peanuts compared to the trap that awaits the participant of the workshop later on.

As things stand, if you're following the workshop at a casual pace, by the time you get to [cleanup](https://www.eksworkshop.com/920_cleanup/eksctl/) you can expect a nasty surprise.

This is my first experience with AWS, not impressed.

**Comment by brentley** [comment]
@johnnybaloney I'm sorry to hear that! 

We've been noodling on how to get the cost down, and these are the ideas that we seem to be circling around:

- swap to T series worker nodes
- swap managed nodegroups to spot priced nodes
- as part of the cloud9 setup, also set a daily billing alarm... something like "alarm if we spend more than $2/day" (amount to be validated)

**Comment by brentley** [comment]
@johnnybaloney can you reach out to me via twitter, or email? twitter: @brentContained and email: blangs@amazon.com
